### ISSUE TITLE
DTLS used in email?

### ISSUE THREAD

**Issue by iwashi** [webrtc-security/webrtc-security.github.io#4]
> DTLS is a standardised protocol which is built into all browsers that support WebRTC, and is one protocol consistently used in web browsers, email, and VoIP platforms to encrypt information. 

Is DTLS used in email? Email is running on TCP.

**Comment by ewanleaver** [comment]
I just have made a mistake when I was researching. A quick google search doesn't back up this information so I deleted the reference to email.

**Comment by iwashi** [comment]
:+1:
